{% set version = "2.1.6" %}

package:
  name: pygrib
  version: {{ version }}

source:
  url: https://github.com/jswhit/pygrib/archive/v{{ version }}rel.tar.gz
  sha256: acb8cb24e3a718e22768db3129788b045a914c32787c550c55fe7fcfe031e940

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cython
    - eccodes
    - jasper
    - libpng
    - numpy
    - pyproj
    - zlib
  run:
    - python
    - setuptools
    - eccodes
    - jasper
    - libpng
    - pyproj
    - zlib

test:
  imports:
    - pygrib
  commands:
    - pip check
    - grib_repack -h
  requires:
    - pip

about:
  home: https://github.com/jswhit/pygrib
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Python GRIB (editions 1 and 2) reader
  doc_url: https://jswhit.github.io/pygrib/
  dev_url: https://github.com/jswhit/pygrib

extra:
  recipe-maintainers:
    - akrherz
    - dopplershift
    - ocefpaf
