{% set version = "2.1.3" %}

package:
  name: pygrib
  version: {{ version }}

source:
  url: https://github.com/jswhit/pygrib/archive/v{{ version }}rel.tar.gz
  sha256: d9b282a5849a518ef2ab047c186edc45669e9642b0b6f1dcdbcde9a17ed02d47

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - eccodes
    - jasper  # [not win]
    - jasper 2.0.14  # [win]
    - libpng
    - numpy
    - pyproj
    - zlib
  run:
    - python
    - setuptools
    - eccodes
    - jasper  # [not win]
    - jasper 2.0.14  # [win]
    - libpng
    - {{ pin_compatible('numpy') }}
    - pyproj
    - zlib

test:
  imports:
    - pygrib
  commands:
    - pip check
    - grib_repack -h
  requires:
    - pip

about:
  home: https://github.com/jswhit/pygrib
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Python GRIB (editions 1 and 2) reader
  doc_url: https://jswhit.github.io/pygrib/
  dev_url: https://github.com/jswhit/pygrib

extra:
  recipe-maintainers:
    - dopplershift
    - ocefpaf
