{%set name = "pygrib" %}
{%set version = "2.0.2" %}
{%set hash_type = "sha256" %}
{%set hash_val = "82eb5e6037217f7ef200521ffc90c59c1db6008ca10d84a5e8ae80008b94ae00" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - python
    - ecmwf_grib
    - jasper
    - libpng >=1.6.28,<1.7
    - pyproj

  run:
    - python
    - ecmwf_grib
    - jasper
    - libpng >=1.6.28,<1.7
    - pyproj
    - numpy

test:
  imports:
    - pygrib
  commands:
    - grib_repack -h
    - conda inspect linkages -p $PREFIX pygrib  # [not win]
    - conda inspect objects -p $PREFIX pygrib  # [osx]

about:
  home: https://github.com/jswhit/pygrib
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Python GRIB (editions 1 and 2) reader.'
  doc_url: https://jswhit.github.io/pygrib/
  dev_url: https://github.com/jswhit/pygrib

extra:
  recipe-maintainers:
    - dopplershift
    - jjhelmus
    - ocefpaf
