{% set version = "2.0.6" %}

package:
  name: pygrib
  version: {{ version }}

source:
  url: https://github.com/jswhit/pygrib/archive/v{{ version }}rel.tar.gz
  sha256: d9327f369a086c88c0d4bc6699b66fe030b365c82d7dd20c4554beff7742b182

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - eccodes
    - jasper 2.0.14  # [win]
    - jasper  # [not win]
    - libpng
    - pyproj
    - zlib
    - numpy
  run:
    - python
    - setuptools
    - eccodes
    - jasper 2.0.14  # [win]
    - jasper  # [not win]
    - libpng
    - numpy
    - pyproj
    - zlib

test:
  imports:
    - pygrib
  commands:
    - pip check
    - grib_repack -h
  requires:
    - pip

about:
  home: https://github.com/jswhit/pygrib
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Python GRIB (editions 1 and 2) reader
  doc_url: https://jswhit.github.io/pygrib/
  dev_url: https://github.com/jswhit/pygrib

extra:
  recipe-maintainers:
    - dopplershift
    - jjhelmus
    - ocefpaf
