# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DXvwtCihY1/2Wt8ceUZkvitQnSswu+Dk3/ULqnFVP9a/HWi+JShQCm1Rjkxn6Bmqrdz/WigexV7i15IH0m6/phOpB5p2gf2wcuHBIU/npMv8i0ZaWw6McF4ctsFErkFl8Dg/kZgPdJNFZQewtWgZeHV0yVucW9HUAGW8a/DdV8pDSHBpvZenoUn3qk3ewzNOMQZrLXmXc+btBC44KOJxKoTCAl4IVvO+wA53wFideBbMsLmAQT+dS9gN3J2Ayu0y+SxBDATMwm/GYVkiSichk2PYK+ftZAwwbZQvsL3Wf/dyXhl43ZS9TYZoIfx0qv3ng2G5oIpAdFODPL2X7zk9MV3z7fOpQdn4r4DuJs2/zTXrEYYcxyj3cYKt+ptjnUp8FehD/HfcN1lUhwEuhjDSqIMw6SmQVHHiuj2MrmRSF/iIVPkp+KFAA35QuK9ApVxmUMKOQh6jSY9DlhRolpmpHJketWFQ6OtiRdfy6dK4ElWm4wFWNnHluHHNpsgJBLBwy7Qy+zf8mPRnzsI4yAFWePHpjXJtRF80AlpRBMei4qZPKYrISm4QbublzP7Kc5GvDrPqx/raluA53BbX2KHKp3VJIvwSSsinIwSutwUpOiu4IR7fwJt52GVUsnRW9lXapCAZ/3PogWBbihutxIPwmgW9HQado7KgN9jse9WXtAk="


before_install:
    - brew remove --force $(brew list)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
