# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DXvwtCihY1/2Wt8ceUZkvitQnSswu+Dk3/ULqnFVP9a/HWi+JShQCm1Rjkxn6Bmqrdz/WigexV7i15IH0m6/phOpB5p2gf2wcuHBIU/npMv8i0ZaWw6McF4ctsFErkFl8Dg/kZgPdJNFZQewtWgZeHV0yVucW9HUAGW8a/DdV8pDSHBpvZenoUn3qk3ewzNOMQZrLXmXc+btBC44KOJxKoTCAl4IVvO+wA53wFideBbMsLmAQT+dS9gN3J2Ayu0y+SxBDATMwm/GYVkiSichk2PYK+ftZAwwbZQvsL3Wf/dyXhl43ZS9TYZoIfx0qv3ng2G5oIpAdFODPL2X7zk9MV3z7fOpQdn4r4DuJs2/zTXrEYYcxyj3cYKt+ptjnUp8FehD/HfcN1lUhwEuhjDSqIMw6SmQVHHiuj2MrmRSF/iIVPkp+KFAA35QuK9ApVxmUMKOQh6jSY9DlhRolpmpHJketWFQ6OtiRdfy6dK4ElWm4wFWNnHluHHNpsgJBLBwy7Qy+zf8mPRnzsI4yAFWePHpjXJtRF80AlpRBMei4qZPKYrISm4QbublzP7Kc5GvDrPqx/raluA53BbX2KHKp3VJIvwSSsinIwSutwUpOiu4IR7fwJt52GVUsnRW9lXapCAZ/3PogWBbihutxIPwmgW9HQado7KgN9jse9WXtAk="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
