travis:
  secure:
    BINSTAR_TOKEN: 3XKcTeUT4ihtwkKFLp3Rb3m1zUYKBUd6tmOb4bu0p2ayU9EkHbbzzLkaoGl2vxBtsf+Pjtp2STyBDvRnrLUZ6a5IYs1qcpTuAx0K8rcQNWKoZHyQzUsPEEcRLpYpnch9oqrSrkGF0nkriYmyfn/Z50oP74S/QI5kFVaeqN6ChXInjfOX61zc8lOIZr9oIZWSxnd4DgMkFaRqcKRikpJGGYbh1bGOIODgyGYqGrvXdgZhvpomJS7LYxA1xga5Nzyo0X5a92x046i5NVZrb83DJNVqjYAv8/WXYljjVel6ndg7GSoHJlYWaLRaakUIRMwFpc95+TiQsxqMdhbdAbQwKQdDbFuMfotcz6H5BgfTeBqVGYDTv/DhKFWBVlY0eQwweMthITGhH2jhCEnWa2aTqzJ1hRYtfsxGQNOeVczPB9cTllGMz6UcSW7v80rLphhAURYgzQh+O9JFPPSf15ypEJjrKauTXrRX0bn4CXDbvrObGzP20PWoDS7Ndz7YNCjbxFaArH828nq6ygZmPiLc2KJWjp49QGiFWMbKJwlyxLI5Zp7G4jLXQLeF7sWrfNi9FY9j3skjxQbRvr2WM0m8lBiA1B4rMXEiPImfUsP2zNVCTjGT3atIG0XaL9Eb+zwR9B5hSMm+U5MyX5x0NtPn8kngBpF+3YtDiBE57iJLxE4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
