travis:
  secure:
    BINSTAR_TOKEN: 20LfSrd0N/RTEsjwvQVZ9qwo39NtvWxr9OgJaXkSM9xWvgECIxjBDfLGK1hrdRgY6jK8OTifR7AGilsbbNU58iMZfYKjhmW5uyo2mi34B8o69iFxZEUKDkGtoVfTu9X35VwBz0biIR/yGNxntSMnxWGpquBkkWn06YAcy/aiWaLQ5Tgf6bEyuN1FOVbECYQrLOr9RS4FQNRjx2y1mKEeeRr4Y1dWLe62qm8GmkGqdZQgvyzdfZhRTLF9Xu0uJnTh+IXiHjfStPsKcgaE05bKcfg5b04XA/3BhSkpErCpu5uBYrDVAKinnK0dYDGv9PNGJ1wHkTn6oWdDOPJQ/KOA98FwFZmEd7Uow0vs5E+Aquz3GgSjiUsMil94G3Shyp/G7xZOFV4Gtsv15zt/O2h43cPB6rpOZmQDAQMQ1ab59o8yoAVg4CCvILOIzth+BHXjadKFK+8Pr2j9+/yBi+mU4WFTe/9dRpppJHi/uhOvXpRq05HrqTpFKrPHgPVjxjcN9TbL7t855TfUXKd5dqJNKXb7kE+yi6GlY/j1+62Dh1ZjGMMm5aJ3WtB/lEa6Z8a0J/65odgyanJsLJd+3BeGLwWlgB7IRnxJqX/Uo8X9caWBy0GLjKTrudp78Qcyl8nnBTBbbo/j9DXawW54wGbphiCw/ySrwuWW6HTKocCE6+g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
