travis:
  secure:
    BINSTAR_TOKEN: OA/q/uZYg5jUv7bhJ5rY+Z3gK5IOAQtIUHv2LDB4NIhpBpvfQQobpVjHK5wJHxUcyGGBuDb2nELckwmRGahswBPfnrV8xUBY7xIsaaAAhIxSVARPA3shmh9ndtiXK3gDjeRBlXn62AvlLovYFlHdknrz1BFZK5xUFkPyN/ltTMGkmJ1S/fN6FFSrbb5tz1zWtxoQy6RryVnAtukI9vD+u/UuB9Y0ORexYDBkC87zFxbR9S4IPmxu0HnYFLfzNuhRoIyZc1M4EGmxAVngpzlm0SBPYZ6BSmvqsldWlg5yoa2VFCNMIB0QzCu0zva/53N+qkZzaK1fS+civlWg8Ld+T8Rj4Q4+s0TsdYpMB5TG5zRZI+f1Mj+DuAniOuRelvX+RNuK8xDU51N+jA+dUEksHMi2vE9F5fxPYSgAqYnf8ah8PYv7ZfDbFNTuLroeMlIj06LTBAPQWtlyh+HxIT600cRBCUmyrV0iTRamUNnEDNITt3VpCg2mKFcfxACFZEOPR4MhxnEYaI8TILO8lspfOCV4KpQzQW7B8VjvcsiELge8s7GYG1nuE5A1jcb/wZZhu4Qak+EMcHRI7cVtbIpv7fgmPTwjZZ8jnUBzD+uwdxJxL3QK1QS0GsCkHNa3zfXlQTDapRi1F+mL3eYKnp1H5lWI7pX048bv+eFnDCJLJ9w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
