travis:
  secure:
    BINSTAR_TOKEN: NMjwrUosIDioYE7D+mEvM5jg2fXPp56nAzENzDSpZOmnePRaE51LIfu3HIuiF8/1z6Ab8huMbae6v0DfQI3I1glyduaCDU8s/JO4IGJtQRt5enzoRqJIFV2HiWp/85ViXuEbz5G7p/2a85qiRVU5dk+PUyS6af0wk0L64Fe18d6nvc1FNA3o5PAAUYcZNuYd0xwpo+vI58dOvTBY16LRWm5fuXhXDuWzJTOoiVU/hBbs6VQMAYL9bDQiL+lqPwCXX4ArbxZkCnjSQYLLewkaCDoRggY9n5gW2zb2O5tUO9PAEGGZQ7cRMz+O7YDq/gYE3Uc6QmxX6qq6M93P6Hrj6gFQSW6s+ufsoTmu9ipW4qSFf3if4ihyLC+XDfsu/lrIC/ncmyY/N9wZiX9V9FBg4F4xq0P3jKX/nCQkyf0KS0FVR2qWp1OgQqj/xm0PxH+9HLg7Q1Bo456W9IqlUj7GmOhi6oXOva1RgW4m/95CxzMWIiSPUS3fBatNfzO3jQneOKR90SplEjDOHMCLcha7mZcMIqZgSxo+17CpJwc7hIoL6P6G/tn3hvH+LZIo6IM+4p5m1/KacYhzcfKJ1GfWBJl6bOOgcnmKMliV/iOvol9kywq1nL3HVcpEQFa1+g3/skp6nqM7/kxRqoOwKOagnMtf0haCMGC0DKpwz1Jm4sQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
