travis:
  secure:
    BINSTAR_TOKEN: DXvwtCihY1/2Wt8ceUZkvitQnSswu+Dk3/ULqnFVP9a/HWi+JShQCm1Rjkxn6Bmqrdz/WigexV7i15IH0m6/phOpB5p2gf2wcuHBIU/npMv8i0ZaWw6McF4ctsFErkFl8Dg/kZgPdJNFZQewtWgZeHV0yVucW9HUAGW8a/DdV8pDSHBpvZenoUn3qk3ewzNOMQZrLXmXc+btBC44KOJxKoTCAl4IVvO+wA53wFideBbMsLmAQT+dS9gN3J2Ayu0y+SxBDATMwm/GYVkiSichk2PYK+ftZAwwbZQvsL3Wf/dyXhl43ZS9TYZoIfx0qv3ng2G5oIpAdFODPL2X7zk9MV3z7fOpQdn4r4DuJs2/zTXrEYYcxyj3cYKt+ptjnUp8FehD/HfcN1lUhwEuhjDSqIMw6SmQVHHiuj2MrmRSF/iIVPkp+KFAA35QuK9ApVxmUMKOQh6jSY9DlhRolpmpHJketWFQ6OtiRdfy6dK4ElWm4wFWNnHluHHNpsgJBLBwy7Qy+zf8mPRnzsI4yAFWePHpjXJtRF80AlpRBMei4qZPKYrISm4QbublzP7Kc5GvDrPqx/raluA53BbX2KHKp3VJIvwSSsinIwSutwUpOiu4IR7fwJt52GVUsnRW9lXapCAZ/3PogWBbihutxIPwmgW9HQado7KgN9jse9WXtAk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
